platform :ios, '8.0'
#use_frameworks!

target 'FZMyLibiary_Example' do
    pod 'FZMyLibiary', :path => '../'
  target 'FZMyLibiary_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
