use_frameworks!

target 'FZMyLibiary_Example' do
    #  pod 'FZMyLibiary', :path => '../'
    pod 'FZMyLibiary', :podspec => '../FZMyLibiary.podspec'
FZMyLibiary.podspec
  target 'FZMyLibiary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
